app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
    issuer: "nordicframtiden"
    accessTokenMinutes: 15

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg-nordidcframtiden-nordicframtiden.h.aivencloud.com:21542/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_yMlMTJgRvoVwdBPFLVi

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false