package com.nordicframtiden.chat;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * A file or image sent in chat. Bytes are stored in Postgres (Cloud Run's
 * filesystem is ephemeral). Rows are created by the upload endpoint before
 * the message exists and are bound to the message when it is sent.
 */
@Entity
@Table(name = "chat_attachment")
public class ChatAttachment {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** Set when the message carrying this attachment is sent. */
  @Column(name = "message_id")
  private Long messageId;

  @Column(name = "uploader_id", nullable = false)
  private Long uploaderId;

  @Column(name = "file_name", nullable = false, length = 255)
  private String fileName;

  @Column(name = "content_type", nullable = false, length = 127)
  private String contentType;

  @Column(name = "size_bytes", nullable = false)
  private Long sizeBytes;

  @Column(nullable = false)
  private byte[] data;

  @Column(name = "created_at", nullable = false)
  private Instant createdAt = Instant.now();

  public Long getId() { return id; }
  /** Test convenience: ids are normally generated by the database. */
  public void setId(Long id) { this.id = id; }
  public Long getMessageId() { return messageId; }
  public void setMessageId(Long messageId) { this.messageId = messageId; }
  public Long getUploaderId() { return uploaderId; }
  public void setUploaderId(Long uploaderId) { this.uploaderId = uploaderId; }
  public String getFileName() { return fileName; }
  public void setFileName(String fileName) { this.fileName = fileName; }
  public String getContentType() { return contentType; }
  public void setContentType(String contentType) { this.contentType = contentType; }
  public Long getSizeBytes() { return sizeBytes; }
  public void setSizeBytes(Long sizeBytes) { this.sizeBytes = sizeBytes; }
  public byte[] getData() { return data; }
  public void setData(byte[] data) { this.data = data; }
  public Instant getCreatedAt() { return createdAt; }
}
