package com.nordicframtiden.api;

import com.nordicframtiden.admin.*;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/admins")
@PreAuthorize("hasRole('ADMIN')")
public class AdminManagementController {

  private final AdminService adminService;

  public AdminManagementController(AdminService adminService) {
    this.adminService = adminService;
  }

  /* =========================
     DTOs
     ========================= */

  // ✅ no password here (generated by backend)
  public record CreateAdminRequest(
      @NotBlank String fullName,
      @NotBlank @Email String email,
      @NotBlank String phone,
      Boolean enabled
  ) {}

  public record UpdateAdminRequest(
      String username,
      String fullName,
      @Email String email,
      String phone,
      Boolean enabled
  ) {}

  // ✅ includes profile fields
  public record AdminResponse(
      Long id,
      String username,
      boolean enabled,
      String fullName,
      String email,
      String phone
  ) {}

  /* =========================
     ENDPOINTS
     ========================= */

  @GetMapping
  public List<AdminResponse> list() {
    return adminService.listAdminsDetailed().stream()
        .map(a -> new AdminResponse(
            a.id(),
            a.username(),
            a.enabled(),
            a.fullName(),
            a.email(),
            a.phone()
        ))
        .toList();
  }

@PostMapping
public AdminResponse create(@RequestBody CreateAdminRequest req) {
  boolean enabled = req.enabled() == null || req.enabled();

  var created = adminService.createAdminWithProfile(
      enabled,
      req.fullName(),
      req.email(),
      req.phone()
  );

  return new AdminResponse(
      created.id(),
      created.username(),
      created.enabled(),
      created.fullName(),
      created.email(),
      created.phone()
  );
}

  @PutMapping("/{id}")
  public AdminResponse update(@PathVariable Long id, @RequestBody UpdateAdminRequest req) {

    var updated = adminService.updateAdminWithProfile(
        id,
        req.username(),
        req.enabled(),
        req.fullName(),
        req.email(),
        req.phone()
    );

    return new AdminResponse(
        updated.id(),
        updated.username(),
        updated.enabled(),
        updated.fullName(),
        updated.email(),
        updated.phone()
    );
  }

  @DeleteMapping("/{id}")
  public void delete(@PathVariable Long id) {
    adminService.deleteAdmin(id);
  }
}