-- V12__create_contact_request.sql
CREATE TABLE contact_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  type VARCHAR(30) NOT NULL,          -- APOTEK | FARMACEUT
  name VARCHAR(160) NOT NULL,
  organization VARCHAR(200),
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(60),

  topic VARCHAR(40) NOT NULL,         -- KONSULTATION | BEMANNING | LON_ERSATTNING | ANNAT
  message VARCHAR(4000) NOT NULL,

  handled BOOLEAN NOT NULL DEFAULT FALSE,
  admin_note VARCHAR(600),

  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  handled_at TIMESTAMP WITH TIME ZONE NULL
);

-- Helpful indexes for admin list filters/sorting
CREATE INDEX idx_contact_request_created_at ON contact_request (created_at DESC);
CREATE INDEX idx_contact_request_handled ON contact_request (handled);
CREATE INDEX idx_contact_request_type ON contact_request (type);
CREATE INDEX idx_contact_request_topic ON contact_request (topic);